name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 */10 * * *'

jobs:
  empty-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create empty commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "Keep app awake"
          git push
